version: 2.1

jobs:
  test:
 
    docker:
      - image: cimg/node:17.1.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: npm run test
      - run: yarn lint
      - run: yarn build
      - run: yarn e2e

workflows:
  orb-free-workflow:
    jobs:
      - test
